/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardcollector;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ywkok
 */
public class admin_product extends javax.swing.JFrame {

    /**
     * Creates new form admin_product
     */
    public admin_product() {
        initComponents();
        SelectProduct();
        SelectCategory();
        GetCategory();
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    public void SelectProduct()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
            St = Con.createStatement();
            Rs = St.executeQuery("Select PROID,PROCATEGORY AS CATEGORY,PRONAME AS SETNAME, PROPURCHASE AS PURCHASE, PROSALE AS PRICE, PROQUANTITY AS QUANTITY from User1.PRODUCTTB");
            ProTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public void SelectCategory()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from User1.CATEGORYTB");
            CartTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
        
    private void GetCategory()
    {
        
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from User1.CATEGORYTB");
            ProCategory.removeAllItems();
            int count = CatFilter.getItemCount();
            for(int i=1;i<count;i++)
            {
                CatFilter.removeItemAt(1);
            }
            while(Rs.next())
            {
                String MyCat = Rs.getString(2);
                CatFilter.addItem(MyCat);
                ProCategory.addItem(MyCat);
            }
            
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    private void filter(String query)
    {
        DefaultTableModel model = (DefaultTableModel)ProTable.getModel();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        ProTable.setRowSorter(tr);
        
        if(query!= "ALL")
        {
            tr.setRowFilter(RowFilter.regexFilter(query));
        }else
        {
            ProTable.setRowSorter(tr);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup_add = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        ProID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ProName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ProQuantity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ProSale = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ProPurchase = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ProCategory = new javax.swing.JComboBox<>();
        Popup_add_cancelbtn = new javax.swing.JButton();
        Popup_add_addbtn = new javax.swing.JButton();
        ProImage = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Popup_adduploadbtn = new javax.swing.JButton();
        Popup_delete = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Popup_delete_cancelbtn = new javax.swing.JButton();
        Popup_delete_deletebtn = new javax.swing.JButton();
        Delete_ID = new javax.swing.JLabel();
        Delete_purchase = new javax.swing.JLabel();
        Delete_category = new javax.swing.JLabel();
        Delete_price = new javax.swing.JLabel();
        Delete_quantity = new javax.swing.JLabel();
        Delete_name = new javax.swing.JLabel();
        Popup_deleteimage = new javax.swing.JLabel();
        Popup_update = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Popup_update_cancelbtn = new javax.swing.JButton();
        Popup_update_updatebtn = new javax.swing.JButton();
        Popup_updateimage = new javax.swing.JLabel();
        Update_ID = new javax.swing.JLabel();
        Update_purchase = new javax.swing.JLabel();
        Update_category = new javax.swing.JLabel();
        Update_name = new javax.swing.JLabel();
        Update_price = new javax.swing.JTextField();
        Update_quantity = new javax.swing.JTextField();
        Popup_cat = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        CatID = new javax.swing.JTextField();
        Popup_catcancel = new javax.swing.JButton();
        Popup_cartadd = new javax.swing.JButton();
        Popup_catdelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CatName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        CartTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Salespage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sellerpage = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CatFilter = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProTable = new javax.swing.JTable();
        ProDeletebtn = new javax.swing.JButton();
        ProUpdatebtn = new javax.swing.JButton();
        ProAddbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        setting = new javax.swing.JLabel();

        Popup_add.setMinimumSize(new java.awt.Dimension(610, 350));
        Popup_add.setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 320));

        ProID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Set Name");

        ProName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProNameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Product ID");

        ProQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProQuantityActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Quantity");

        ProSale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProSaleActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Category");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Purchase Price");

        ProPurchase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProPurchaseActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Sale Price");

        ProCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL" }));
        ProCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProCategoryActionPerformed(evt);
            }
        });

        Popup_add_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_add_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_add_cancelbtn.setText("CANCEL");
        Popup_add_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_add_cancelbtnActionPerformed(evt);
            }
        });

        Popup_add_addbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_add_addbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_add_addbtn.setText("ADD");
        Popup_add_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_add_addbtnActionPerformed(evt);
            }
        });

        ProImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProImageActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Product image");

        Popup_adduploadbtn.setText("+");
        Popup_adduploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_adduploadbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Popup_add_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ProImage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Popup_adduploadbtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(ProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(ProSale, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(ProPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(ProCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(455, Short.MAX_VALUE)
                    .addComponent(Popup_add_addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProID)
                    .addComponent(ProCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Popup_adduploadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Popup_add_cancelbtn)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(248, Short.MAX_VALUE)
                    .addComponent(Popup_add_addbtn)
                    .addGap(21, 21, 21)))
        );

        javax.swing.GroupLayout Popup_addLayout = new javax.swing.GroupLayout(Popup_add.getContentPane());
        Popup_add.getContentPane().setLayout(Popup_addLayout);
        Popup_addLayout.setHorizontalGroup(
            Popup_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_addLayout.setVerticalGroup(
            Popup_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Popup_delete.setMinimumSize(new java.awt.Dimension(610, 350));
        Popup_delete.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Product ID       ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Category          ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Set Name         ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Quantity            ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sale Price          ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Purchase Price  ");

        Popup_delete_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_delete_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_delete_cancelbtn.setText("CANCEL");
        Popup_delete_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_delete_cancelbtnActionPerformed(evt);
            }
        });

        Popup_delete_deletebtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_delete_deletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_delete_deletebtn.setText("DELETE");
        Popup_delete_deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_delete_deletebtnActionPerformed(evt);
            }
        });

        Delete_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_ID.setText(":  ");

        Delete_purchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_purchase.setText(":  ");

        Delete_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_category.setText(":  ");

        Delete_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_price.setText(":  ");

        Delete_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_quantity.setText(":  ");

        Delete_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_name.setText(":  ");

        Popup_deleteimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Popup_deleteimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Popup_delete_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Popup_delete_deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete_category, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_price, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Delete_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Delete_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Delete_category))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Delete_quantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Delete_price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Delete_purchase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Popup_deleteimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Popup_delete_cancelbtn)
                    .addComponent(Popup_delete_deletebtn))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout Popup_deleteLayout = new javax.swing.GroupLayout(Popup_delete.getContentPane());
        Popup_delete.getContentPane().setLayout(Popup_deleteLayout);
        Popup_deleteLayout.setHorizontalGroup(
            Popup_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_deleteLayout.setVerticalGroup(
            Popup_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Popup_update.setMinimumSize(new java.awt.Dimension(610, 350));
        Popup_update.setUndecorated(true);
        Popup_update.setPreferredSize(new java.awt.Dimension(481, 278));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Product ID       ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Category          ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Set Name         ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Quantity            ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Sale Price          ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Purchase Price  ");

        Popup_update_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_update_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_update_cancelbtn.setText("CANCEL");
        Popup_update_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_update_cancelbtnActionPerformed(evt);
            }
        });

        Popup_update_updatebtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_update_updatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_update_updatebtn.setText("UPDATE");
        Popup_update_updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_update_updatebtnActionPerformed(evt);
            }
        });

        Popup_updateimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Update_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_ID.setText(":  ");

        Update_purchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_purchase.setText(":  ");

        Update_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_category.setText(":  ");

        Update_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_name.setText(":  ");

        Update_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_priceActionPerformed(evt);
            }
        });

        Update_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_quantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(Popup_update_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Popup_updateimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Update_price, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Update_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Popup_update_updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update_name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update_category, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 62, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Update_ID))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(Update_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(Update_category))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(Update_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Update_purchase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(Update_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Popup_updateimage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Popup_update_cancelbtn)
                    .addComponent(Popup_update_updatebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Popup_updateLayout = new javax.swing.GroupLayout(Popup_update.getContentPane());
        Popup_update.getContentPane().setLayout(Popup_updateLayout);
        Popup_updateLayout.setHorizontalGroup(
            Popup_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_updateLayout.setVerticalGroup(
            Popup_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Popup_cat.setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMinimumSize(new java.awt.Dimension(600, 320));

        CatID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatIDActionPerformed(evt);
            }
        });

        Popup_catcancel.setBackground(new java.awt.Color(255, 255, 255));
        Popup_catcancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_catcancel.setText("CANCEL");
        Popup_catcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_catcancelActionPerformed(evt);
            }
        });

        Popup_cartadd.setBackground(new java.awt.Color(255, 255, 255));
        Popup_cartadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_cartadd.setText("ADD");
        Popup_cartadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_cartaddActionPerformed(evt);
            }
        });

        Popup_catdelete.setBackground(new java.awt.Color(255, 255, 255));
        Popup_catdelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_catdelete.setText("Delete");
        Popup_catdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_catdeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Categories List");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ID");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Name");

        CatName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatNameActionPerformed(evt);
            }
        });

        CartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        CartTable.setRowHeight(30);
        CartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(CartTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Popup_catcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(Popup_cartadd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Popup_catdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CatName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CatID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Popup_catcancel)
                    .addComponent(Popup_cartadd)
                    .addComponent(Popup_catdelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Popup_catLayout = new javax.swing.GroupLayout(Popup_cat.getContentPane());
        Popup_cat.getContentPane().setLayout(Popup_catLayout);
        Popup_catLayout.setHorizontalGroup(
            Popup_catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Popup_catLayout.setVerticalGroup(
            Popup_catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cards60px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 151, 95));
        jLabel3.setText("Card Collection ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 151, 95));
        jLabel4.setText("Hobby Store");

        Salespage.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Salespage.setForeground(new java.awt.Color(255, 255, 255));
        Salespage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salespage.setText("Sales");
        Salespage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalespageMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 151, 90));
        jLabel5.setText("Product");

        Sellerpage.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Sellerpage.setForeground(new java.awt.Color(255, 255, 255));
        Sellerpage.setText("Seller");
        Sellerpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerpageMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/exit.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(94, 94, 94))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salespage)
                            .addComponent(Sellerpage)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logout)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2))
                .addGap(81, 81, 81)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(Sellerpage)
                .addGap(39, 39, 39)
                .addComponent(Salespage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(24, 24, 24))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setText("Product Management");

        CatFilter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CatFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL" }));
        CatFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatFilterActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Categories Filter");

        jScrollPane1.setBackground(new java.awt.Color(50, 151, 90));
        jScrollPane1.setForeground(new java.awt.Color(50, 151, 90));

        ProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Category", "Set Name", "Purchase", "Sale", "Quantity"
            }
        ));
        ProTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ProTable.setRowHeight(25);
        ProTable.setSelectionBackground(new java.awt.Color(55, 151, 90));
        ProTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProTable);

        ProDeletebtn.setBackground(new java.awt.Color(255, 255, 255));
        ProDeletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProDeletebtn.setText("DELETE");
        ProDeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProDeletebtnActionPerformed(evt);
            }
        });

        ProUpdatebtn.setBackground(new java.awt.Color(255, 255, 255));
        ProUpdatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProUpdatebtn.setText("UPDATE");
        ProUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProUpdatebtnActionPerformed(evt);
            }
        });

        ProAddbtn.setBackground(new java.awt.Color(255, 255, 255));
        ProAddbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProAddbtn.setText("ADD");
        ProAddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProAddbtnActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/settings.png"))); // NOI18N
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ProAddbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(ProUpdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(ProDeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(155, 155, 155))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CatFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setting)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setting)
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CatFilter)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProUpdatebtn)
                            .addComponent(ProDeletebtn)
                            .addComponent(ProAddbtn))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CatFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatFilterActionPerformed
        // TODO add your handling code here:
        String query = CatFilter.getSelectedItem().toString();
        filter (query);
    }//GEN-LAST:event_CatFilterActionPerformed

    private void ProDeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProDeletebtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProTable.getModel();
        int Myindex = ProTable.getSelectedRow();
        if(Myindex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select the Product to be delete");
        }else
        {
            Delete_ID.setText(model.getValueAt(Myindex,0).toString());
            Delete_name.setText(model.getValueAt(Myindex, 2).toString());
            Delete_category.setText(model.getValueAt(Myindex, 1).toString());
            Delete_quantity.setText(model.getValueAt(Myindex,5).toString());
            Delete_purchase.setText(model.getValueAt(Myindex,3).toString());
            Delete_price.setText(model.getValueAt(Myindex,4).toString());
             try
            {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                St = Con.createStatement();
                Rs = St.executeQuery("Select PROIMAGE from User1.PRODUCTTB where PROID="+model.getValueAt(Myindex,0).toString());
                String filename = "";
                if(Rs.next())
                {
                    filename = Rs.getString(1);
                    if(!filename.isEmpty())
                    {
                        ImageIcon icon = new ImageIcon(filename);
                        //Image image = icon.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
                        Popup_deleteimage.setIcon(icon);
                       
                    }else
                    {
                        Popup_deleteimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/sportcard.jpg")));
                    }
                }
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            Popup_delete.pack();
            Popup_delete.setLocationRelativeTo(null);
            Popup_delete.setVisible(true);
        }
        
    }//GEN-LAST:event_ProDeletebtnActionPerformed

    private void ProUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProUpdatebtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProTable.getModel();
        int Myindex = ProTable.getSelectedRow();
        if(Myindex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select the Product to be update");
        }else
        {
            
            Update_ID.setText(model.getValueAt(Myindex,0).toString());
            Update_name.setText(model.getValueAt(Myindex, 2).toString());
            Update_category.setText(model.getValueAt(Myindex, 1).toString());
            Update_quantity.setText(model.getValueAt(Myindex,5).toString());
            Update_purchase.setText(model.getValueAt(Myindex,3).toString());
            Update_price.setText(model.getValueAt(Myindex,4).toString());
            
            try
            {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                St = Con.createStatement();
                Rs = St.executeQuery("Select PROIMAGE from User1.PRODUCTTB where PROID="+model.getValueAt(Myindex,0).toString());
                String filename = "";
                if(Rs.next())
                {
                    filename = Rs.getString(1);
                    if(!filename.isEmpty())
                    {
                        ImageIcon icon = new ImageIcon(filename);
                        //Image image = icon.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
                        Popup_updateimage.setIcon(icon);
                       
                    }else
                    {
                        Popup_updateimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/sportcard.jpg")));
                    }
                }
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            
            Popup_update.pack();
            Popup_update.setLocationRelativeTo(null);
            Popup_update.setVisible(true);
        }
    }//GEN-LAST:event_ProUpdatebtnActionPerformed

    private void ProAddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProAddbtnActionPerformed
        // TODO add your handling code here:
        Popup_add.pack();
        Popup_add.setLocationRelativeTo(null);
        Popup_add.setVisible(true);
    }//GEN-LAST:event_ProAddbtnActionPerformed

    private void ProIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProIDActionPerformed

    private void ProNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProNameActionPerformed

    private void ProQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProQuantityActionPerformed

    private void ProSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProSaleActionPerformed

    private void ProPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProPurchaseActionPerformed

    private void Popup_add_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_add_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_add.setVisible(false);
        ProID.setText("");
        ProName.setText("");
        ProPurchase.setText("");
        ProSale.setText("");
        ProQuantity.setText("");
    }//GEN-LAST:event_Popup_add_cancelbtnActionPerformed

    private void Popup_add_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_add_addbtnActionPerformed
        // TODO add your handling code here:
        int log = 0;
        try
        {
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
            St = Con.createStatement();
             if(ProID.getText().isEmpty() || ProName.getText().isEmpty()||ProPurchase.getText().isEmpty()||ProQuantity.getText().isEmpty()||ProSale.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Missing Information");
            }
            else
            {
                Rs = St.executeQuery("Select PROID from User1.PRODUCTTB");
                while(Rs.next())
                {
                    if(ProID.getText().equals(Rs.getString(1)))
                    {
                        JOptionPane.showMessageDialog(this,"Duplicate Product ID!!");
                        log = 1;
                    }
                }
                if(log == 0){
                    String image = ProImage.getText();
                    image = image.replace("\\","\\\\");
                    
                    PreparedStatement add = Con.prepareStatement("insert into PRODUCTTB values(?,?,?,?,?,?,?)");
                    add.setInt(1, Integer.valueOf(ProID.getText()));
                    add.setString(2, ProCategory.getSelectedItem().toString());
                    add.setString(3, ProName.getText());
                    add.setInt(4, Integer.valueOf(ProPurchase.getText()));
                    add.setInt(5, Integer.valueOf(ProSale.getText()));
                    add.setInt(6, Integer.valueOf(ProQuantity.getText()));
                    add.setString(7,image);
                    int row = add.executeUpdate();
                    Popup_add.setVisible(false);
                    JOptionPane.showMessageDialog(this,"Product Added Successfully");
                    Con.close();
                    ProID.setText("");
                    ProName.setText("");
                    ProPurchase.setText("");
                    ProSale.setText("");
                    ProQuantity.setText("");
                    SelectProduct();
                }
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }


    }//GEN-LAST:event_Popup_add_addbtnActionPerformed

    private void Popup_delete_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_delete_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_delete.setVisible(false);
    }//GEN-LAST:event_Popup_delete_cancelbtnActionPerformed

    private void Popup_delete_deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_delete_deletebtnActionPerformed
        // TODO add your handling code here:
        try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                String ProductID = Delete_ID.getText();
                String Query = "Delete from User1.PRODUCTTB where PROID="+ProductID;
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                SelectProduct();
                JOptionPane.showMessageDialog(this,"Product Deleted Successfully");
                Popup_delete.setVisible(false);
            }catch(Exception e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_Popup_delete_deletebtnActionPerformed

    private void Popup_update_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_update_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_update.setVisible(false);
    }//GEN-LAST:event_Popup_update_cancelbtnActionPerformed

    private void Popup_update_updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_update_updatebtnActionPerformed
        // TODO add your handling code here:
        if(Update_price.getText().isEmpty() && Update_quantity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        {
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                String Query = "Update User1.PRODUCTTB set PROSALE="+Update_price.getText()+",PROQUANTITY="+Update_quantity.getText()+"where PROID="+Update_ID.getText();
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                SelectProduct();
                JOptionPane.showMessageDialog(this,"Product Updated");
                Popup_update.setVisible(false);
            }catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Popup_update_updatebtnActionPerformed

    private void Update_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_priceActionPerformed

    private void SellerpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerpageMouseClicked
        // TODO add your handling code here:
        reg.adminform2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerpageMouseClicked

    private void SalespageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalespageMouseClicked
        // TODO add your handling code here:
        reg.adminform3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalespageMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        reg.loginform1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void Update_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_quantityActionPerformed

    private void CatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatIDActionPerformed

    private void Popup_catcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_catcancelActionPerformed
        GetCategory();
        Popup_cat.setVisible(false);
        
    }//GEN-LAST:event_Popup_catcancelActionPerformed

    private void Popup_cartaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_cartaddActionPerformed
        if(CatID.getText().isEmpty() || CatName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }else
        {
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                PreparedStatement add = Con.prepareStatement("insert into CATEGORYTB values(?,?)");
                add.setInt(1, Integer.valueOf(CatID.getText()));
                add.setString(2, CatName.getText());
                add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Category Added Successfully");
                Con.close();
                CatID.setText("");
                CatName.setText("");
                SelectCategory();
                }catch (Exception e)
                {
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_Popup_cartaddActionPerformed

    private void Popup_catdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_catdeleteActionPerformed

        
        if(CatID.getText().isEmpty() || CatName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        { 
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/CardCollectordb","User1","user1");
                String CID = CatID.getText();
                String Query = "Delete from USER1.CATEGORYTB where CATID="+CID;
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                SelectCategory();
                JOptionPane.showMessageDialog(this,"Category Deleted Successfully");
                Con.close();
                CatID.setText("");
                CatName.setText("");
            }catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Popup_catdeleteActionPerformed

    private void CatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatNameActionPerformed

    }//GEN-LAST:event_CatNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Popup_cat.pack();
        Popup_cat.setLocationRelativeTo(null);
        Popup_cat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)CartTable.getModel();
        int Myindex = CartTable.getSelectedRow();
        if(Myindex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select the Category to be delete");
        }else
        {
            CatID.setText(model.getValueAt(Myindex,0).toString());
            CatName.setText(model.getValueAt(Myindex, 1).toString());
        }
    }//GEN-LAST:event_CartTableMouseClicked

    private void ProCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProCategoryActionPerformed

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        // TODO add your handling code here:
        reg.adminform4.setVisible(true);
    }//GEN-LAST:event_settingMouseClicked

    private void ProImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProImageActionPerformed

    private void Popup_adduploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_adduploadbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ProImage.setText(filename);
        /*Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(50,50,Image.SCALE_SMOOTH);
        Popup_deleteimage.setIcon(icon);
        Popup_updateimage.setIcon(icon);
        */
        /*        
        String image = txtfilename.getText();
        image = image.replace"\\","\\\\");
        */
    }//GEN-LAST:event_Popup_adduploadbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CartTable;
    private javax.swing.JComboBox<String> CatFilter;
    private javax.swing.JTextField CatID;
    private javax.swing.JTextField CatName;
    private javax.swing.JLabel Delete_ID;
    private javax.swing.JLabel Delete_category;
    private javax.swing.JLabel Delete_name;
    private javax.swing.JLabel Delete_price;
    private javax.swing.JLabel Delete_purchase;
    private javax.swing.JLabel Delete_quantity;
    private javax.swing.JLabel Logout;
    private javax.swing.JDialog Popup_add;
    private javax.swing.JButton Popup_add_addbtn;
    private javax.swing.JButton Popup_add_cancelbtn;
    private javax.swing.JButton Popup_adduploadbtn;
    private javax.swing.JButton Popup_cartadd;
    private javax.swing.JDialog Popup_cat;
    private javax.swing.JButton Popup_catcancel;
    private javax.swing.JButton Popup_catdelete;
    private javax.swing.JDialog Popup_delete;
    private javax.swing.JButton Popup_delete_cancelbtn;
    private javax.swing.JButton Popup_delete_deletebtn;
    private javax.swing.JLabel Popup_deleteimage;
    private javax.swing.JDialog Popup_update;
    private javax.swing.JButton Popup_update_cancelbtn;
    private javax.swing.JButton Popup_update_updatebtn;
    private javax.swing.JLabel Popup_updateimage;
    private javax.swing.JButton ProAddbtn;
    private javax.swing.JComboBox<String> ProCategory;
    private javax.swing.JButton ProDeletebtn;
    private javax.swing.JTextField ProID;
    private javax.swing.JTextField ProImage;
    private javax.swing.JTextField ProName;
    private javax.swing.JTextField ProPurchase;
    private javax.swing.JTextField ProQuantity;
    private javax.swing.JTextField ProSale;
    private javax.swing.JTable ProTable;
    private javax.swing.JButton ProUpdatebtn;
    private javax.swing.JLabel Salespage;
    private javax.swing.JLabel Sellerpage;
    private javax.swing.JLabel Update_ID;
    private javax.swing.JLabel Update_category;
    private javax.swing.JLabel Update_name;
    private javax.swing.JTextField Update_price;
    private javax.swing.JLabel Update_purchase;
    private javax.swing.JTextField Update_quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel setting;
    // End of variables declaration//GEN-END:variables
}
